# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 19) do

  create_table "board_titles", :force => true do |t|
    t.column "description", :string, :limit => 50, :null => false
  end

  create_table "dues_types", :force => true do |t|
    t.column "description", :string, :limit => 50, :null => false
  end

  create_table "events", :force => true do |t|
    t.column "title",           :string
    t.column "description",     :text
    t.column "start_date_time", :datetime
    t.column "end_date_time",   :datetime
    t.column "created_at",      :datetime, :default => '2007-12-01 00:00:00', :null => false
    t.column "updated_at",      :datetime, :default => '2007-12-01 00:00:00', :null => false
  end

  create_table "households", :force => true do |t|
    t.column "old_id",   :integer,               :null => false
    t.column "name",     :string,  :limit => 50, :null => false
    t.column "line1",    :string,  :limit => 50, :null => false
    t.column "line2",    :string,  :limit => 50
    t.column "city",     :string,  :limit => 50, :null => false
    t.column "state_id", :integer,               :null => false
    t.column "zip_code", :string,  :limit => 10, :null => false
  end

  create_table "join_requests", :force => true do |t|
    t.column "first_name",     :string,   :limit => 50, :null => false
    t.column "middle_name",    :string,   :limit => 50
    t.column "last_name",      :string,   :limit => 50, :null => false
    t.column "line1",          :string,   :limit => 50, :null => false
    t.column "line2",          :string,   :limit => 50
    t.column "city",           :string,   :limit => 50, :null => false
    t.column "state_id",       :integer,                :null => false
    t.column "zip_code",       :string,   :limit => 10, :null => false
    t.column "home_phone",     :string,   :limit => 20
    t.column "business_phone", :string,   :limit => 20
    t.column "mobile_phone",   :string,   :limit => 20
    t.column "email_address",  :string,   :limit => 50
    t.column "dues_amount",    :decimal,                :null => false
    t.column "why_interested", :text
    t.column "created_at",     :datetime,               :null => false
    t.column "updated_at",     :datetime,               :null => false
  end

  create_table "member_levels", :force => true do |t|
    t.column "description", :string, :limit => 50, :null => false
  end

  create_table "members", :force => true do |t|
    t.column "household_id",    :integer,                :null => false
    t.column "first_name",      :string,   :limit => 50, :null => false
    t.column "last_name",       :string,   :limit => 50, :null => false
    t.column "home_phone",      :string,   :limit => 20
    t.column "business_phone",  :string,   :limit => 20
    t.column "mobile_phone",    :string,   :limit => 20
    t.column "email_address",   :string,   :limit => 50
    t.column "member_level_id", :integer,                :null => false
    t.column "board_title_id",  :integer,                :null => false
    t.column "created_at",      :datetime,               :null => false
    t.column "updated_at",      :datetime,               :null => false
  end

  create_table "pages", :force => true do |t|
    t.column "title",   :string
    t.column "content", :text
  end

  create_table "sightings", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "entry_date",  :date
  end

  create_table "states", :force => true do |t|
    t.column "code", :string, :limit => 2,  :null => false
    t.column "name", :string, :limit => 50, :null => false
  end

  create_table "stories", :force => true do |t|
    t.column "headline",   :string,                             :null => false
    t.column "byline",     :string, :default => "FOLVHP Board", :null => false
    t.column "content",    :text,                               :null => false
    t.column "created_on", :date,                               :null => false
    t.column "updated_on", :date,                               :null => false
  end

  create_table "uploaded_files", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "is_public",    :boolean,  :default => false
    t.column "created_at",   :datetime, :default => '2007-09-22 10:37:08', :null => false
    t.column "updated_at",   :datetime, :default => '2007-09-22 10:37:08', :null => false
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
